# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
  # Based on Ubuntu 18.04
  config.vm.box = "generic/ubuntu1804"
  config.vm.box_check_update = false

  # Provider-specific: RAM and CPU
  config.vm.provider :libvirt do |v|
    v.qemuargs :value => '-machine'
    v.qemuargs :value => 'accel=kvm'
    v.qemuargs :value => '-cpu'
    v.qemuargs :value => 'host'
    # 1G of RAM
    v.qemuargs :value => '-m'
    v.qemuargs :value => '1G'
    # Allocate guest RAM with huge pages
    # QEMU will create a file to serve as the guest RAM and allow another process to map that file.
    v.qemuargs :value => '-object'
    v.qemuargs :value => 'memory-backend-file,id=mem,size=1G,share=on,mem-path=/mnt/huge'
    v.qemuargs :value => '-mem-prealloc'
    v.qemuargs :value => '-numa'
    v.qemuargs :value => 'node,memdev=mem'
  end

  # Add MoonGen code
  config.vm.provision "file", source: "./moongen/", destination: "~/"
  # Add host public key
  config.vm.provision "file", source: "/root/.ssh/id_rsa.pub", destination: "~/host_public_key.pub"
  # Install software
  config.vm.provision :shell, :path => "vagrant-docker-vm-install.sh"
end
